from policies.bernoulli_policy import BernoulliPolicy
from policies.normal_policy import NormalPolicy
from policies.discrete_policy import DiscretePolicy
from policies.squashed_gaussian_policy import SquashedGaussianPolicy
from policies.cnn_policy import CnnPolicy
from policies.generic_net import GenericNet
from policies.policy_wrapper import PolicyWrapper